DROP TABLE IF EXISTS "PRTL_EFFECT_ANAL";
DROP TABLE IF EXISTS "PRTL_EFFECT_ANAL_DETAIL";
DROP TABLE IF EXISTS "PRTL_EFFECT_ANAL_ERR";
DROP TABLE IF EXISTS "PRTL_DATA_RLT_ANAL";


CREATE TABLE "ILM"."PRTL_EFFECT_ANAL" 
   (	"ANAL_ID" NUMBER NOT NULL ENABLE, 
	"REG_CLS_CD" VARCHAR2(100 BYTE),
	"PRG_CLS_CD" VARCHAR2(100 BYTE), 
        "SYSTEM_ID" VARCHAR2(100 BYTE),
	"SQL_ID" VARCHAR2(500 BYTE), 
        "PARENT_CLASS_NM" VARCHAR2(1000 BYTE),
        "PARENT_METHOD_NM" VARCHAR2(1000 BYTE),
        "CLASS_CLS_CD" VARCHAR2(100 BYTE),
	"CLASS_NM" VARCHAR2(1000 BYTE), 
	"METHOD_NM" VARCHAR2(1000 BYTE), 
	"SQL_XML_NM" VARCHAR2(1000 BYTE), 
        "JOB_ID" VARCHAR2(500 BYTE),
        "STEP_ID" VARCHAR2(500 BYTE),
        "JOB_XML_NM" VARCHAR2(1000 BYTE),
	"SQL_CLS_CD" VARCHAR2(100 BYTE),
	"SQL_STATEMENT" CLOB, 
	"PROG_NM" VARCHAR2(200 BYTE), 
	"PROG_DESC" VARCHAR2(4000 BYTE), 
        "HANDMADE_CLS_CD" VARCHAR2(100 BYTE),
	"CLERK_NO" VARCHAR2(100 BYTE), 
	"REG_DTTM" DATE, 
	"LAST_UPDT_DTTM" DATE, 
	 CONSTRAINT "PRTL_EFFECT_ANAL_" PRIMARY KEY ("ANAL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 10485760 NEXT 10485760 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "ILM_DAT"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 10485760 NEXT 10485760 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "ILM_DAT" 
 LOB ("SQL_STATEMENT") STORE AS (
  TABLESPACE "ILM_DAT" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 10485760 NEXT 10485760 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) ;
 
   COMMENT ON COLUMN "ILM"."PRTL_EFFECT_ANAL"."ANAL_ID" IS '분석ID';
 
   COMMENT ON COLUMN "ILM"."PRTL_EFFECT_ANAL"."REG_CLS" IS '등록구분';
 
   COMMENT ON COLUMN "ILM"."PRTL_EFFECT_ANAL"."PRG_CLS_CD" IS '프로그램구분코드';
   
   COMMENT ON COLUMN "ILM"."PRTL_EFFECT_ANAL"."SYSTEM_ID" IS '시스템 ID';
 
   COMMENT ON COLUMN "ILM"."PRTL_EFFECT_ANAL"."SQL_ID" IS 'SQLID';
 
   COMMENT ON COLUMN "ILM"."PRTL_EFFECT_ANAL"."PARENT_CLASS_NM" IS '호출 클래스명';
   
   COMMENT ON COLUMN "ILM"."PRTL_EFFECT_ANAL"."PARENT_METHOD_NM" IS '호출 메서드명';
   
   COMMENT ON COLUMN "ILM"."PRTL_EFFECT_ANAL"."CLASS_CLS_CD" IS '클래스 구분 코드';
 
   COMMENT ON COLUMN "ILM"."PRTL_EFFECT_ANAL"."CLASS_NM" IS '클래스명';
 
   COMMENT ON COLUMN "ILM"."PRTL_EFFECT_ANAL"."METHOD_NM" IS '메소드명';
 
   COMMENT ON COLUMN "ILM"."PRTL_EFFECT_ANAL"."SQL_XML_NM" IS 'SQL XML명';
   
   COMMENT ON COLUMN "ILM"."PRTL_EFFECT_ANAL"."JOB_ID" IS 'JOB 명';
   
   COMMENT ON COLUMN "ILM"."PRTL_EFFECT_ANAL"."STEP_ID" IS 'STEP 명';
   
   COMMENT ON COLUMN "ILM"."PRTL_EFFECT_ANAL"."JOB_XML_NM" IS 'JOB XML 명';
 
   COMMENT ON COLUMN "ILM"."PRTL_EFFECT_ANAL"."SQL_CLS_CD" IS 'SQL구분코드';
 
   COMMENT ON COLUMN "ILM"."PRTL_EFFECT_ANAL"."SQL_STATEMENT" IS 'SQL구문';
 
   COMMENT ON COLUMN "ILM"."PRTL_EFFECT_ANAL"."PROG_NM" IS '프로그램명';
 
   COMMENT ON COLUMN "ILM"."PRTL_EFFECT_ANAL"."PROG_DESC" IS '프로그램설명';
   
   COMMENT ON COLUMN "ILM"."PRTL_EFFECT_ANAL"."HANDMADE_CLS_CD" IS '수작업 유형 코드';
 
   COMMENT ON COLUMN "ILM"."PRTL_EFFECT_ANAL"."CLERK_NO" IS '담당자';
 
   COMMENT ON COLUMN "ILM"."PRTL_EFFECT_ANAL"."REG_DTTM" IS '입력일자';
 
   COMMENT ON COLUMN "ILM"."PRTL_EFFECT_ANAL"."LAST_UPDT_DTTM" IS '최종수정일자';
 
   COMMENT ON TABLE "ILM"."PRTL_EFFECT_ANAL"  IS '영향도분석';
   
   
 CREATE TABLE "ILM"."PRTL_EFFECT_ANAL_DETAIL" 
   (	"ANAL_ID" NUMBER NOT NULL ENABLE, 
	"ANAL_DETAIL_SEQ" NUMBER NOT NULL ENABLE, 
	"TABLE_NM" VARCHAR2(200 BYTE), 
	"COLUMN_NM" VARCHAR2(200 BYTE), 
	 CONSTRAINT "PRTL_EFFECT_ANAL_DETAIL_" PRIMARY KEY ("ANAL_ID", "ANAL_DETAIL_SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 10485760 NEXT 10485760 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "ILM_DAT"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 10485760 NEXT 10485760 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "ILM_DAT" ;
 
   COMMENT ON COLUMN "ILM"."PRTL_EFFECT_ANAL_DETAIL"."ANAL_ID" IS '분석ID';
 
   COMMENT ON COLUMN "ILM"."PRTL_EFFECT_ANAL_DETAIL"."ANAL_DETAIL_SEQ" IS '순번';
 
   COMMENT ON COLUMN "ILM"."PRTL_EFFECT_ANAL_DETAIL"."TABLE_NM" IS '테이블명';
 
   COMMENT ON COLUMN "ILM"."PRTL_EFFECT_ANAL_DETAIL"."COLUMN_NM" IS '컬럼명';
 
   COMMENT ON TABLE "ILM"."PRTL_EFFECT_ANAL_DETAIL"  IS '영향도분석상세';
   

   
     CREATE TABLE PRTL_EFFECT_ANAL_ERR 
(
   ANAL_ERR_SEQ  NUMBER  NOT NULL ,  
   ERR_CLS_CD  VARCHAR2(100 BYTE),
   ERR_STATUS  VARCHAR2(2)    ,  
   ERR_MSG  VARCHAR2(500 BYTE)    ,  
   CLASS_NM  VARCHAR2(500 BYTE)    ,  
   XML_NM  VARCHAR2(500 BYTE)    ,  
   SQL_ID  VARCHAR2(300 BYTE)    ,  
   SQL_STATEMENT  CLOB    ,  
   REG_DTTM  DATE     
);


CREATE TABLE "ILM"."PRTL_DATA_RLT_ANAL" 
   (	"DATA_RLT_ANAL_ID" NUMBER NOT NULL ENABLE, 
        "PRG_CLS_CD" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
        "PJT_NM" VARCHAR2(200 BYTE), 
        "SQL_ANAL_CNT" NUMBER, 
        "SQL_ANAL_SUCC" NUMBER, 
        "SQL_ANAL_FAIL" NUMBER, 
        "JAVA_CNT" NUMBER, 
        "XML_CNT" NUMBER,
        "INSERT_CNT" NUMBER,
	"SELECT_CNT" NUMBER, 
	"DELETE_CNT" NUMBER, 
        "MERGE_CNT" NUMBER, 
        "UPDATE_CNT" NUMBER, 
        "START_DTTM" DATE, 
        "END_DTTM" DATE,
        
	 CONSTRAINT "PRTL_DATA_RLT_ANAL" PRIMARY KEY ("DATA_RLT_ANAL_ID") 
         
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 10485760 NEXT 10485760 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "ILM_DAT"  ENABLE ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 10485760 NEXT 10485760 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "ILM_DAT" ;
 
   COMMENT ON COLUMN "ILM"."PRTL_DATA_RLT_ANAL"."DATA_RLT_ANAL_ID" IS '관계분석SEQ';
 
   COMMENT ON COLUMN "ILM"."PRTL_DATA_RLT_ANAL"."PRG_CLS_CD" IS '프로그램 구분 코드';
 
   COMMENT ON COLUMN "ILM"."PRTL_DATA_RLT_ANAL"."PJT_NM" IS '프로젝트명';
 
   COMMENT ON COLUMN "ILM"."PRTL_DATA_RLT_ANAL"."SQL_ANAL_CNT" IS 'SQL 분석 건수';
   
   COMMENT ON COLUMN "ILM"."PRTL_DATA_RLT_ANAL"."SQL_ANAL_SUCC" IS 'SQL 분석 성공';
   
   COMMENT ON COLUMN "ILM"."PRTL_DATA_RLT_ANAL"."SQL_ANAL_FAIL" IS 'SQL 분석 실패';
   
   COMMENT ON COLUMN "ILM"."PRTL_DATA_RLT_ANAL"."JAVA_CNT" IS 'JAVA 파일 수';
   
   COMMENT ON COLUMN "ILM"."PRTL_DATA_RLT_ANAL"."XML_CNT" IS 'XML 수';
   
   COMMENT ON COLUMN "ILM"."PRTL_DATA_RLT_ANAL"."INSERT_CNT" IS 'INSERT건수';
   
   COMMENT ON COLUMN "ILM"."PRTL_DATA_RLT_ANAL"."SELECT_CNT" IS 'SELECT건수';
   
   COMMENT ON COLUMN "ILM"."PRTL_DATA_RLT_ANAL"."DELETE_CNT" IS 'DELETE건수';
   
   COMMENT ON COLUMN "ILM"."PRTL_DATA_RLT_ANAL"."UPDATE_CNT" IS 'UPDATE건수';
   
   COMMENT ON COLUMN "ILM"."PRTL_DATA_RLT_ANAL"."MERGE_CNT" IS 'MERGE건수';
   
   COMMENT ON COLUMN "ILM"."PRTL_DATA_RLT_ANAL"."START_DTTM" IS '분석시작일시';
   
   COMMENT ON COLUMN "ILM"."PRTL_DATA_RLT_ANAL"."END_DTTM" IS '분석 종료일시';
 
   COMMENT ON TABLE "ILM"."PPRTL_DATA_RLT_ANAL"  IS '데이터 관계 분석';
   
   --DROP TABLE IF EXISTS PRTL03TB;
--DROP TABLE IF EXISTS PRTL02TB;
--DROP TABLE IF EXISTS PRTL01TB;
--
--
--CREATE TABLE PRTL01TB (
--  SQL_ID varchar(150) NOT NULL COMMENT "SQL 아이디",
--  CLASS_NM varchar(200) NOT NULL COMMENT "클래스 명",
--  METHOD_NM varchar(400) NOT NULL COMMENT "메소드 명 ",
--  XML_PATH varchar(200) NOT NULL COMMENT "xml 파일명",
--  SQL_CLS_CD varchar(6) NOT NULL COMMENT "SQL 구분코드",
--  PRG_CLS_CD varchar(6) NOT NULL COMMENT "프로그램 구분 코드",
--  REG_CLS char(1) NOT NULL COMMENT "등록구분",
--  SQL_STATEMENT TEXT(65535) NOT NULL COMMENT "SQL 구문",
--  INPUT_DTTM DATETIME NOT NULL COMMENT "입력일자",
--  LAST_UPDATE_DTTM DATETIME NOT NULL COMMENT "최종수정일자",
--  PRIMARY KEY (SQL_ID,CLASS_NM,METHOD_NM,XML_PATH , SQL_CLS_CD)
--) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8 COMMENT="SQL 영향도분석결과";
--
--CREATE TABLE PRTL02TB (
--  FK_SQL_ID varchar(150) NOT NULL COMMENT "SQL아이디",
--  FK_CLASS_NM varchar(200) NOT NULL COMMENT "클래스 명",
--  FK_METHOD_NM varchar(400) NOT NULL COMMENT "메소드 명",
--  FK_XML_PATH varchar(200) NOT NULL COMMENT "xml 파일명",
--  TABLE_NM varchar(50) NOT NULL COMMENT "테이블명",
--  SEQ_NUM INT NOT NULL COMMENT "순번",
--  COLUMN_NM varchar(200) COMMENT "컬럼명",
--  INPUT_DTTM DATETIME NOT NULL COMMENT "입력일자",
--  LAST_UPDATE_DTTM DATETIME NOT NULL COMMENT "최종수정일자",
--  PRIMARY KEY (FK_SQL_ID, FK_CLASS_NM, FK_METHOD_NM, FK_XML_PATH, TABLE_NM, SEQ_NUM ),
--  CONSTRAINT SQL_CONSTRAINT FOREIGN KEY (FK_SQL_ID, FK_CLASS_NM, FK_METHOD_NM, FK_XML_PATH) REFERENCES PRTL01TB(SQL_ID, CLASS_NM, METHOD_NM, XML_PATH) ON UPDATE CASCADE ON DELETE CASCADE
--) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8 COMMENT="SQL 영향도분석결과 상세";
--
--CREATE TABLE PRTL03TB (
--  SEQ_NUM INT NOT NULL AUTO_INCREMENT COMMENT "순번",
--  CLASS_NM varchar(200) COMMENT "클래스 명",
--  XML_PATH varchar(200) COMMENT "xml 파일명",
--  STATUS char(1) NOT NULL COMMENT "오류 처리 상태",
--  EXCEPTION_CLS varchar(20) NOT NULL COMMENT "오류 구분",
--  EXCEPTION_MSG varchar(500) NOT NULL COMMENT "오류 내용",
--  SQL_ID varchar(150) COMMENT "SQL 아이디",
--  SQL_STATEMENT TEXT(65535) COMMENT "SQL 구문",
--  INPUT_DTTM DATETIME NOT NULL COMMENT "입력일자",
--  LAST_UPDATE_DTTM DATETIME NOT NULL COMMENT "최종수정일자",
--  PRIMARY KEY (SEQ_NUM)
--) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT="SQL 영향도분석실패 결과";
--

   
   
